### ISSUE TITLE
fetchAssoc() seems to return only one (the last) row

### ISSUE THREAD

**Issue by cxj** [auraphp/Aura.Sql#100]
The documentation says:

```
// fetchAssoc() returns an associative array of all rows where the key is the
// first column, and the row arrays are keyed on the column names
$result = $pdo->fetchAssoc($stm, $bind);
```

However, only one row is returned, nominally the last row, rather than "all rows".  Incorrect docs?  Bug in code?

**Comment by iansltx** [comment]
Do you have distinct first-column values in your use case? See:

https://github.com/auraphp/Aura.Sql/blob/2.x/src/ExtendedPdo.php#L392

If you do, we've got a bug, since this should behave like a rekeyed version of fetchAll().

**Comment by iansltx** [comment]
One thing that should be fine but _might_ not be: https://github.com/auraphp/Aura.Sql/blob/2.x/src/ExtendedPdo.php#L422 using current() rather than reset(). The latter is guaranteed to grab the first column in the record, while the former has no reason not to be the first column, but doesn't have quite as strong of a guarantee. Can someone with a better understanding of array iteration semantics chime in here?

Probably fine though, since the test that would catch weirdness here passes on PHP5, PHP7 and HHVM...

**Comment by cxj** [comment]
Looks like my problem was actually that the first column I was selecting might or might not be unique, so latter rows were overwriting the former.
