### ISSUE TITLE
class complexity reduction ideas

### ISSUE THREAD

**Issue by pavarnos** [auraphp/Aura.Sql#114]
Don't want to over-step my welcome here. Just wanted to toss a random idea at you to see if you like it...

phpStorm / php mess detector warn that the class is quite complex.

![screen shot 2016-03-07 at 11 05 27 am](https://cloud.githubusercontent.com/assets/589595/13557479/1492263e-e456-11e5-9409-4f6f690e5ca5.png)

To some extent this is to be expected: it is the nature of this kind of component. But I wondered if a couple of simple refactorings might reduce that complexity and offer a slight performance boost. 
1. Split the polymorphic constructor into a separate class. Make the main ExtendedPdo class take only a proper PDO dsn as its only parameter. Create a LazyExtendedPdo class that extends ExtendedPdo and move the username, password, options, attributes member variables there. Override connect() and disconnect() appropriately. The injected member variable is no longer needed.
2. Split responsibility for profiling out to a separate class. To do this, create a DecoratingExtendedPdo class as a decorator that has 

``` php
/** ExtendedPdoInterface */
protected $wrapped;

public function __constructor(ExtendedPdoInterface $wrapped) {
    $this->wrapped = $wrapped;
}
```

and proxies all its method calls to the $wrapped class. Create a ProfiledExtendedPdo class that extends DecoratedExtendedPdo and wraps each method call appropriately eg

``` php
public function rollBack()  {
    $this->beginProfile(__FUNCTION__);
    $result = $this->wrapped->rollBack();     
    $this->endProfile();
    return $result;
}
```

Then ExtendedPdo does not need to know about the profiler.

What do you think? Happy to submit 2 separate pull requests if that is helpful...

**Comment by pmjones** [comment]
Not overstepping your welcome at all. Yes, it's definitely a complex class, one of the most complex in Aura. A lot of that is because it extends PDO, rather than being "its own thing".

Let's get the yield() stuff in place first, then we can revisit this more thoroughly.

In the mean time:
- The separate classes and constructors for a wrapped PDO vs a lazy-instantiated PDO sounds like it has merit.
- I am considering dropping the profiling as it is, and replacing it with a PSR-3 logging implementation.

Thanks for the critique on this.

**Comment by pavarnos** [comment]
lol. was going to suggest a PSR-3 logger but didn't want to overstep my welcome even further...

**Comment by pmjones** [comment]
Great minds :-)

**Comment by pavarnos** [comment]
hmmm... i just spent a couple of hours implementing LazyExtendedPdo to see what would happen. It ended up being 760 lines of fairly useless php: most of the functions look like

``` php
    public function fetchValue($statement, array $values = [])
    {
        $this->connect();
        return $this->pdo->fetchValue($statement, $values);
    }
```

where $this->connect() creates a new ExtendedPdo.
An alternative is to use __call() and @method so code completion works, but i'm not so keen on magic. I'd rather have plain obvious code. 

Pull request follows, with a couple of caveats
- ExtendedPdo was a PDO in its own right _and_ it proxied to an private PDO (so there were two PDO objects per ExtendedPdo). Now the private PDO is no longer needed.
- added fetchGroup() and prepareWithValues() to ExtendedPdoInterface because they are part of the public interface of ExtendedPdo 
- ... then LazyExtendedPdo can just implement the ExtendedPdoInterface and not have to inherit from anything.
- ExtendedPdo::query() needed to be rewritten. See the comments in the code

**Comment by pmjones** [comment]
@pavarnos All right, on to the Profiling work.

Yes, we definitely want to replace it with a PSR-3 typehint, and inject a PSR-3 logger instead of the existing profiler. My initial intution is that ProfiledExtendedPdo can create the message and pass the profile information as context.

One of the use-cases is to be able to turn logging on and off at particular points the codebase, so merely passing a ProfiledExtendedPdo may not be enough; there will need to be "turn profiling on" and "turn profiling" off functionality.

Further, we may need to consider the possibility that the profiling/logging is better as part of ExtendedPdo itself, and not as a separate class.

**Comment by pavarnos** [comment]
OK. How did you want the messages to look? Something like

``` php
private $logLevel = \Psr\Log\LogLevel::DEBUG;
private $logger;
public function__construct(\Psr\Log\LoggerInterface $logger) {
   ....
}

public function endProfile($statement, $values) {
    if (!$this->enabled) return;
    $this->logger->log($this->level,$this->profile['function'],['time' => microtime(true) - $this->profile['time'],, 'statement' => $statement, 'values' => $values]);
}
```

**Comment by pavarnos** [comment]
looks like we covered everything here. closing for now. feel free to re-open if needed
