### ISSUE TITLE
Provide a profile formatter/dumper

### ISSUE THREAD

**Issue by mlaphp** [auraphp/Aura.Sql#98]
It would be nice to have a class that automatically formats and outputs the profiler data for easier reading.

**Comment by pavarnos** [comment]
this is resolved by #120?

**Comment by pmjones** [comment]
I think #120 is the start. It occurs to me that:
1. we need the backtrace in the logging/profiling, so we can track back to where the query came from (I've found that super-useful in the past); and,
2. instead of a "message prefix", we need a "formatting line" with placeholders tokens; that way different users can log different things.

Does that make sense?

**Comment by pavarnos** [comment]
re 1: yeah it would be handy. But Monolog makes it trivially easy to add a BacktraceProcessor (for example) to add stack traces to a channel. Trivial to write. Why add it here?

2 sounds great. much more flexible. Would be nice to have a separate "channel id" value somewhere so it is easy to distinguish which channel it came from in your ConnectionLocator

**Comment by pmjones** [comment]
> 1 ... Monolog makes it trivially easy to add a BacktraceProcessor (for example) to add stack traces to a channel.

I was not aware of that; I'll have to take a look at it.  Even so, I'd prefer to rely only on PSR-3, not on a particular implementation of it.

> 2 sounds great. 

Good deal; I'll see what I can do, unless you get to it first.

**Comment by pavarnos** [comment]
Monolog: LineFormatter::includeStacktraces()

**Comment by pmjones** [comment]
This should be fixed with recent pushes to the 3.x branch; cf. the new Profiler::setLogFormat() et al. methods.
